### ISSUE TITLE
отсутствует файл /etc/init.d/chroot_debian.sh

### ISSUE THREAD

**Issue by engr0** [MyBookLive/chroot#1]
после запуска скрипта на свежеустановленную прошивку(v03.04.01-230) 
WDMyCloud:~# wget https://github.com/MyBookLive/chroot/raw/master/install.sh
WDMyCloud:~# sudo sh /root/install.sh
по окончании процесса установки выдаёт ошибки:

 =>  Do you wish to start chroot'ed services right now [y/n]?y
/root/install.sh: line 118: /etc/init.d/chroot_debian.sh: No such file or directory
/root/install.sh: line 120: /etc/init.d/chroot_debian.sh: No such file or directory

сам файл скрипта  - chroot_debian.sh пустой и лежит в /DataVolume/debian/

**Comment by dm38** [comment]
Только что проверил, на My Book Live - работает. Что происходит у Вас - не могу предположить...

**Comment by engr0** [comment]
при запуске install.sh из-за ругани на сертификаты скрипт был запущен с --no-check-certificate
но файл wedro_chroot.sh при таком способе запуска не скачался и не лёг куда надо.

**Comment by ryzhovau** [comment]
@dm38, мы оба проверяли на твоей прошивке. Не исключаю, что на заводской с Debian 5 всё так и есть.

@engr0, пожалуйста, проверьте ход установки снова:

```
wget --no-check-certificate https://github.com/MyBookLive/chroot/raw/master/install.sh
sh ./install.sh debian2
```

Где `debian2` - имя папки в `/DataVolume`, куда будет установлена ещё одна копия среды. После тестов её можно будет удалить по [этому алгоритму](https://github.com/MyBookLive/chroot/wiki/Using#%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-chroot-%D1%81%D1%80%D0%B5%D0%B4%D1%8B).

**Comment by engr0** [comment]
после установки

WDMyCloud:~# /etc/init.d/chroot_debian2.sh stop
-bash: /etc/init.d/chroot_debian2.sh: No such file or directory

в директории /DataVolume/debian2 лежит пустой файл chroot_debian2.sh т.е. всё как и было неделю назад

**Comment by ryzhovau** [comment]
Значит подождём более делального отчёта от кого-либо ещё с заводской прошивкой, т.к. перепрошиваться ради воспроизведения глюка ни у меня ни у @dm38 желания нет. На альтернативной прошивке всё в порядке.

**Comment by twocolors** [comment]
@ryzhovau а вы на прошивки ув.Alexey S ?

**Comment by ryzhovau** [comment]
На прошивку что? Перешёл ли? На одном устройстве да, на другом — нет.

**Comment by ryzhovau** [comment]
Раз нет обратной связи, то закрываю.
