### ISSUE TITLE
Alternate OS?

### ISSUE THREAD

**Issue by Efreak** [MyBookLive/chroot#2]
How difficult would it be to use Ubuntu Server or Fedora or instead of Debian? Not that I have anything against Debian, I'd just prefer for some of my packages to be more up to date.

It would also be interesting to see about using UML (or something else) instead of simply chrooting. Specifically, keeping files and processes separate would be nice (from the program's view, not so much for security).

**Comment by ryzhovau** [comment]
> How difficult would it be to use Ubuntu Server or Fedora or instead of Debian? Not that I have anything against Debian, I'd just prefer for some of my packages to be more up to date.

You may use any distro with PPC platform support in similar way.

> It would also be interesting to see about using UML (or something else) instead of simply chrooting. 

Not sure it can provided by host (Debian 5?) system.

**Comment by Efreak** [comment]
> Not sure it can provided by host (Debian 5?) system.

It absolutely can. I just can't compile it within the development environment they provide, since there's not enough memory etc. The simplest way to just `export ARCH=um` and compile the linux kerrnel as usual (`make defconfig && make menuconfig && make`)
