### ISSUE TITLE
Error installing bash/dash.

### ISSUE THREAD

**Issue by Efreak** [MyBookLive/chroot#3]
```
I: Configuring bash...
W: Failure while configuring required packages.
W: See /DataVolume/debian/debootstrap/debootstrap.log for details (possibly the package package is at fault)
sed: can't read /DataVolume/debian/etc/locale.gen: No such file or directory
chroot: failed to run command `locale-gen': No such file or directory
 Info: A Debian jessie chroot environment installed.
 Info: Now deploying services start script...
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match chroot_debian.sh Default-Stop values (0 6)
 Info: ...finished.
 =>  Do you wish to install miniDLNA UPnP/DLNA server [y/n]?
```

Full install.sh output [here](https://gist.github.com/a3997471a3200a8d85d4); full debootstrap.log uploaded [here](https://gist.github.com/95f2a2eed34726b478fc).

This is a problem. Bash and dash get installed early. Apt-get and aptitude are not installed yet, making it difficult to continue the install. Theoretically I could install with dpkg, but that would be rather time-consuming.

**Comment by Efreak** [comment]
Also, the script should understand that something failed and _stop_. It doesn't stop on errors, including things like a corrupt/incomplete download of debootstrap at the very beginning (it still worked for me because this wasn't the first time I'd run it)

```
install.sh: line 50: 21996 Aborted                 $WGET /tmp/$debootstrapPkgName $projectURL/$debootstrapPkgName
dpkg-deb: error: `/tmp/debootstrap_1.0.48+deb7u4_all.deb' is not a debian format archive
dpkg: error processing /tmp/debootstrap_1.0.48+deb7u4_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/debootstrap_1.0.48+deb7u4_all.deb
```

**Comment by ryzhovau** [comment]
I managed to reproduce just one warning about bash, this bug can be fixed with `apt-get install bash` in chroot'ed environment. 

We receive similar reports from time to time. Sometimes debootstrap fails to install new environment at all! It depends on current state of Debian repo, I'm afraid. There is nothing we can do about that.

**Comment by Efreak** [comment]
> this bug can be fixed with `apt-get install bash` in chroot'ed environment.

I can't do this because apt-get never installed. I am rebuilding the chroot _again_, so I guess I'll report back again when it's done. At least I finally have apt-cacher-ng working on windows (cygwin).

**Comment by Efreak** [comment]
This is the same thing I had before. Apt-get never gets installed. You can see the full log [here](https://gist.github.com/Efreak/918d4ca9dd2c8e3684ec).

Since bash is actually installed in the chroot, it seems that the error must be the package immediately after it, libbz2 (bzip2), which shouldn't be needed by the bootstrap process. Is there some way to manually specify a different version that will hopefully install correctly? I'm finding it difficult to search for this as most results turn up basic usage of installing various OS versions (debian, ubuntu) with deboostrap, and the [manpage](http://linux.die.net/man/8/debootstrap) isn't terribly helpful.

**Comment by ryzhovau** [comment]
Closing for now. We not going to develop or support MBL anymore.
