### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by trendoman** [MyBookLive/chroot#4]
Привет,

У меня такая же ошибка: https://github.com/glennhickey/progressiveCactus/issues/93 

> Connecting to github.com|192.30.253.112|:443... connected. 
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
 Unable to establish SSL connection.

Что можно предпринять? Обновить wget (если это безопасно)?
Прошивка MyBookLiveDuo 02.43.09-038 : Core F/W, если это имеет значение..

Thx

**Comment by goldstar611** [comment]
Maybe try to extract wget binary from new Debian package to check if old wget is problem? https://packages.debian.org/jessie/powerpc/wget/download

**Comment by trendoman** [comment]
@goldstar611 Thank you, this is what I got in ssh session (stock, no chroot yet):

> MEGA:~# apt-get install wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run `apt-get -f install' to correct these:
The following packages have unmet dependencies:
  e2fsprogs: PreDepends: e2fslibs (= 1.41.12-2) but 1.42.5-1.1+deb7u1 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

Perhaps, I should try upgrading wget some other way?

**Comment by goldstar611** [comment]
Yes, Debian OS on MyBookLive is broken. Try manual unpack to access updated wget binary. https://unix.stackexchange.com/questions/138188/easily-unpack-deb-edit-postinst-and-repack-deb

**Comment by trendoman** [comment]
Awesome. I had success with the deb from Wheezy (initially suggested Jessie version failed): https://packages.debian.org/wheezy/powerpc/wget/download
It was pretty easily unpacked with 7-zip (Win32). Following did the trick:

> mv /usr/bin/wget /usr/bin/wget.bak
mv /DataVolume/shares/Public/wget /usr/bin/wget

Thanks again, @goldstar611 and @ryzhovau for the scripts and support.
